### ISSUE TITLE
There is no image with 0.1 version on docker.io

### ISSUE THREAD

**Issue by djkormo** [little-angry-clouds/prometheus-data-generator#4]
littleangryclouds/prometheus-data-generator:0.1

**Comment by nvtkaszpir** [comment]
I've added my own fork (no changes yet) to quay.io, so please try https://quay.io/repository/kaszpir/prometheus-data-generator?tab=tags from master

**Comment by alexppg** [comment]
I've pushed already, thanks! https://hub.docker.com/layers/littleangryclouds/prometheus-data-generator/0.1/images/sha256-6ac1c5ee29a75e99cc2361a3a951694a8aaee76107346f64013dfdd9380a9d87?context=explore
